spring.application.name=todozao
##spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.core.env=DEBUG
api.security.token.secret=${JWT_SECRET:my-secret-key}

spring.datasource.url=jdbc:postgresql://localhost:5432/todozao
spring.datasource.username=postgres
spring.datasource.password=futebol4123

# Como rodar localmente no IntelliJ:
# Configure as variaveis de ambiente da execucao com algo como:
# DATABASE_URL=jdbc:postgresql://localhost:5432/todozao;DATABASE_USERNAME=postgres;DATABASE_PASSWORD=sua_senha